### ISSUE TITLE
cannot ssh into fabric8-java-docker

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8-java-docker#1]
is there a specific reason why the user/pw for fabric8 user has been commented out?

https://github.com/fabric8io/fabric8-java-docker/blob/master/Dockerfile#L19

**Comment by davsclaus** [comment]
@jimmidyson wonder if this is something you know about - although maybe keep the image as now as it works for us ;)

**Comment by jimmidyson** [comment]
Link is no longer to valid line of code, but we shouldn't have ssh enabled anyway as it uses up too much redundant resource. `docker exec` or `osc exec` are better options.
