### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8-java-docker#2]
Trying using docker running under vagrant on a Mac.

vagrant@precise64:~$ docker logs 54f43e22a237eda7793230e04a1539a8e730d5353d14d12eb95eee9d094eea14
Welcome to fabric8: http://fabric8.io/

Environment variables:
FABRIC8_JAVA_AGENT=-javaagent:jolokia-agent.jar=host=0.0.0.0
FABRIC8_JVM_ARGS=-Dlog4j.configuration=etc/log4j.properties
HOME=/
HOSTNAME=54f43e22a237
JAVA_HOME=/usr/lib/jvm/jre
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/fabric8
SHLVL=2
TERM=xterm
_=/usr/bin/env

executing java -javaagent:jolokia-agent.jar=host=0.0.0.0 -Dlog4j.configuration=etc/log4j.properties -cp classes:lib/*  
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://172.17.0.5:8778/jolokia/
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32	  use a 32-bit data model if available
    -d64	  use a 64-bit data model if available
    -server	  to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A : separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.
vagrant@precise64:~$

**Comment by davsclaus** [comment]
We have been using this image for quite some time now and it works well for our java standalone apps.

I am closing this one assuming it works now.
